# Generated by Django 3.2.6 on 2021-08-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210810_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
